---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-pod
  strategy:
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service-pod
    spec:
      containers:
      - name: user-service
        image: subratohld/user-service:COMMIT_ID
        imagePullPolicy: Never  # Fetch image from local registry (Always/Never/IfNotPresent)
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 5
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: "128Mi"
          limits:
            cpu: 500m
            memory: "1Gi"
      volumes:
      - name: config-volume
        configMap:
          name: user-svc-cm
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service-pod
  ports:
  - name: http
    port: 8080
    targetPort: 8080
