---
# Use this service when your mysql server is running
# outside of your kubernetes cluster
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
subsets:
  - addresses:
    - ip: 192.168.222.254  # Server ip where database server is running
    ports:
      - port: 3306  # Server port where database server is running
